apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Component
  annotations:
     backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring boot
    - event consumer
  type: microservice
  visibility: public
  display:
    website:
      title: Event Handler
      url: https://google.com/

spec:
  type: microservice
  owner: Team
  lifecycle: experimental
